<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DevLiteServer</AssemblyName>
    <RootNamespace>DevLiteServer</RootNamespace>
    <Title>Dev Lite Server</Title>
    <Product>Dev Lite Server</Product>
    <Description>Fast, portable, lightweight local web development environment for Windows (WEMP stack)</Description>
    <Company>Dev Lite Server</Company>
    <Version>1.0.0</Version>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>

</Project>
