using System.Text;

namespace DevLiteServer.Core;

public record VirtualHostItem(
    string FolderName,
    string Domain,
    string PhysicalPath,
    string DocumentRoot, // If public/ or htdocs/ exists, point there (Laravel/Symfony style)
    bool HasPublicSubfolder
);

public static class VirtualHostManager
{
    private const string HostsMarkerStart = "# DEV LITE SERVER VHOSTS START";
    private const string HostsMarkerEnd = "# DEV LITE SERVER VHOSTS END";

    public static List<VirtualHostItem> DetectVirtualHosts(string appRoot)
    {
        var list = new List<VirtualHostItem>();
        string wwwDir = Path.Combine(appRoot, "www");
        if (!Directory.Exists(wwwDir)) return list;

        foreach (var dir in Directory.GetDirectories(wwwDir))
        {
            string folderName = Path.GetFileName(dir);
            if (string.IsNullOrWhiteSpace(folderName) || folderName.StartsWith('.')) continue;

            // Normalize domain: e.g. "my-project" -> "my-project.test"
            string domain = $"{folderName.ToLowerInvariant()}.test";

            // Check for modern framework document root (Laravel/Symfony/Slim: /public, or /htdocs)
            string publicDir = Path.Combine(dir, "public");
            string htdocsDir = Path.Combine(dir, "htdocs");

            string docRoot = dir;
            bool hasPublic = false;
            if (Directory.Exists(publicDir))
            {
                docRoot = publicDir;
                hasPublic = true;
            }
            else if (Directory.Exists(htdocsDir))
            {
                docRoot = htdocsDir;
                hasPublic = true;
            }

            list.Add(new VirtualHostItem(folderName, domain, dir, docRoot, hasPublic));
        }

        return list;
    }

    public static void GenerateVhostsConfig(string appRoot, AppConfig config, string nginxConfDir)
    {
        var vhosts = DetectVirtualHosts(appRoot);
        string vhostsOutputFile = Path.Combine(nginxConfDir, "vhosts.conf");

        var sb = new StringBuilder();
        sb.AppendLine("# Automatically generated by Dev Lite Server. Do not edit manually.");
        sb.AppendLine();

        string templatePath = Path.Combine(appRoot, "templates", "vhost.conf.tpl");
        string template = File.Exists(templatePath)
            ? File.ReadAllText(templatePath)
            : @"server {
    listen {{HTTP_PORT}};
    server_name {{DOMAIN}};
    root ""{{PROJECT_ROOT}}"";
    index index.php index.html index.htm;
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:{{PHP_PORT}};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}";

        foreach (var vhost in vhosts)
        {
            string forwardRoot = vhost.DocumentRoot.Replace('\\', '/');
            string serverBlock = template
                .Replace("{{HTTP_PORT}}", config.HttpPort.ToString())
                .Replace("{{PHP_PORT}}", config.PhpFastCgiPort.ToString())
                .Replace("{{DOMAIN}}", vhost.Domain)
                .Replace("{{PROJECT_ROOT}}", forwardRoot);

            sb.AppendLine(serverBlock);
            sb.AppendLine();
        }

        File.WriteAllText(vhostsOutputFile, sb.ToString());
    }

    public static bool NeedsHostsSync(string appRoot)
    {
        var vhosts = DetectVirtualHosts(appRoot);
        string hostsPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "drivers", "etc", "hosts");
        if (!File.Exists(hostsPath)) return false;

        try
        {
            string currentHosts = File.ReadAllText(hostsPath);
            foreach (var vhost in vhosts)
            {
                if (!currentHosts.Contains(vhost.Domain, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
        }
        catch
        {
            return false;
        }

        return false;
    }

    public static async Task<bool> SyncHostsFileBatchAsync(string appRoot)
    {
        var vhosts = DetectVirtualHosts(appRoot);
        string hostsPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "drivers", "etc", "hosts");
        if (!File.Exists(hostsPath)) return false;

        string currentHosts;
        try
        {
            currentHosts = await File.ReadAllTextAsync(hostsPath);
        }
        catch (Exception)
        {
            return false;
        }

        // Build desired vhosts block
        var blockSb = new StringBuilder();
        blockSb.AppendLine(HostsMarkerStart);
        foreach (var vhost in vhosts)
        {
            blockSb.AppendLine($"127.0.0.1 {vhost.Domain}");
        }
        blockSb.Append(HostsMarkerEnd);

        string newHosts;
        int startIndex = currentHosts.IndexOf(HostsMarkerStart, StringComparison.OrdinalIgnoreCase);
        int endIndex = currentHosts.IndexOf(HostsMarkerEnd, StringComparison.OrdinalIgnoreCase);

        if (startIndex >= 0 && endIndex >= 0)
        {
            endIndex += HostsMarkerEnd.Length;
            newHosts = currentHosts.Substring(0, startIndex).TrimEnd() + "\n\n" + blockSb.ToString() + "\n" + currentHosts.Substring(endIndex).TrimStart();
        }
        else
        {
            newHosts = currentHosts.TrimEnd() + "\n\n" + blockSb.ToString() + "\n";
        }

        if (newHosts.Trim() == currentHosts.Trim())
        {
            return true; // Already up-to-date
        }

        // Write via temp script elevated with 1 single UAC prompt
        string tempScript = Path.Combine(Path.GetTempPath(), $"sync_hosts_{Guid.NewGuid():N}.ps1");
        string tempContentFile = Path.Combine(Path.GetTempPath(), $"hosts_content_{Guid.NewGuid():N}.txt");

        try
        {
            await File.WriteAllTextAsync(tempContentFile, newHosts, Encoding.UTF8);

            string scriptContent = $@"
$ErrorActionPreference = 'Stop'
$content = [System.IO.File]::ReadAllText('{tempContentFile.Replace("'", "''")}')
[System.IO.File]::WriteAllText('{hostsPath.Replace("'", "''")}', $content, [System.Text.Encoding]::UTF8)
";
            await File.WriteAllTextAsync(tempScript, scriptContent, Encoding.UTF8);

            var psi = new System.Diagnostics.ProcessStartInfo
            {
                FileName = "powershell.exe",
                Arguments = $"-NoProfile -ExecutionPolicy Bypass -File \"{tempScript}\"",
                UseShellExecute = true,
                Verb = "runas", // Triggers single UAC elevation
                WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden
            };

            using var proc = System.Diagnostics.Process.Start(psi);
            if (proc == null) return false;
            await proc.WaitForExitAsync();
            return proc.ExitCode == 0;
        }
        catch
        {
            return false;
        }
        finally
        {
            try { if (File.Exists(tempScript)) File.Delete(tempScript); } catch { }
            try { if (File.Exists(tempContentFile)) File.Delete(tempContentFile); } catch { }
        }
    }
}
